### ISSUE TITLE
How to do Auth with Quip Automation API?

### ISSUE THREAD

**Issue by elsigh** [wernervz/watson-quip-translation-toolbar-app#1]
How can a Live App authenticate with the Quip Automation API and get a bearer access token?

**Comment by elsigh** [comment]
Hey Werner,

I've made a quick demo/example app that shows how you can get the Platform API OAuth2 bearer token in your Live App. This should get you what you're looking for in order to pass the token off to a proxy app that can make calls using the Automation API (which doesn't support CORS today).

Let me know if you have any questions about it!

**Comment by wernervz** [comment]
Hi @elsigh, how can I get access to the demo/example code?
